{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ask-nlp-robot.serviceAccountName" . }}
  namespace: {{ .Release.Name }}
  labels:
    {{- include "ask-nlp-robot.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
